-- below i will list loadstrings for the options all of this code will be in comments so this file cannot be executed


-- paid executors

-- pottasium = loadstring(game:HttpGet("https://raw.githubusercontent.com/random-projects-by-breif/chat-tags/refs/heads/main/Paid%20executors/pottasium.luau"))()

-- awp.gg = loadstring(game:HttpGet("https://raw.githubusercontent.com/random-projects-by-breif/chat-tags/refs/heads/main/Paid%20executors/awp.gg.luau"))()

-- volcano paid = loadstring(game:HttpGet("https://raw.githubusercontent.com/random-projects-by-breif/chat-tags/refs/heads/main/Paid%20executors/volcano%20paid.luau"))()

-- wave = loadstring(game:HttpGet("https://raw.githubusercontent.com/random-projects-by-breif/chat-tags/refs/heads/main/Paid%20executors/wave.luau"))()

-- zenith = loadstring(game:HttpGet("https://raw.githubusercontent.com/random-projects-by-breif/chat-tags/refs/heads/main/Paid%20executors/zenith.luau"))()

-- Free executors =

-- xeno = loadstring(game:HttpGet("https://raw.githubusercontent.com/random-projects-by-breif/chat-tags/refs/heads/main/free%20executors/xeno.luau"))()

-- solara = loadstring(game:HttpGet("https://raw.githubusercontent.com/random-projects-by-breif/chat-tags/refs/heads/main/free%20executors/solara.luau"))()

-- velocity = loadstring(game:HttpGet("https://raw.githubusercontent.com/random-projects-by-breif/chat-tags/refs/heads/main/free%20executors/velocity.luau"))()

-- volcano free = loadstring(game:HttpGet("https://raw.githubusercontent.com/random-projects-by-breif/chat-tags/refs/heads/main/free%20executors/volcano%20free%20.luau"))()

-- bunni.lol user loadstring(game:HttpGet("https://raw.githubusercontent.com/random-projects-by-breif/chat-tags/refs/heads/main/free%20executors/bunni.lol.luau"))()
